from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from app.schemas.risk import RiskLevel


class EventType(str, Enum):
    VOICE_INTEGRITY = "VOICE_INTEGRITY"
    SPEAKER_VERIFICATION = "SPEAKER_VERIFICATION"
    ASR = "ASR"
    CONVERSATION_ANALYSIS = "CONVERSATION_ANALYSIS"
    CONTEXT_ENGINE = "CONTEXT_ENGINE"
    RISK_UPDATE = "RISK_UPDATE"
    SECURITY_ALERT = "SECURITY_ALERT"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ASR_UPDATED = "ASR_UPDATED"
    SPEAKER_ANALYSIS_UPDATED = "SPEAKER_ANALYSIS_UPDATED"
    SPOOF_ANALYSIS_UPDATED = "SPOOF_ANALYSIS_UPDATED"
    SOCIAL_ENGINEERING_UPDATED = "SOCIAL_ENGINEERING_UPDATED"
    SECURITY_FINDING = "SECURITY_FINDING"
    RECOMMENDATION_UPDATED = "RECOMMENDATION_UPDATED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ANALYSIS_ERROR = "ANALYSIS_ERROR"



class SecurityEvent(BaseModel):
    """
    Structured security event generated by the AI processing pipeline.
    Designed for real-time WebSocket push to frontend consoles.
    """
    event_id: str = Field(..., description="Unique event ID")
    session_id: str = Field(..., description="Associated call session ID")
    timestamp: str = Field(..., description="ISO timestamp or session offset timestamp")
    event_type: EventType = Field(..., description="Categorical event type")
    source: str = Field(..., description="Originating AI component or service")
    severity: RiskLevel = Field(..., description="Event severity (LOW, MEDIUM, HIGH)")
    message: str = Field(..., description="Concise human-readable event description")
    confidence: Optional[float] = Field(None, ge=0, le=1.0, description="Model detection confidence (0.0 - 1.0)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Structured contextual metadata")
