import {
  LiveCall,
  RiskSignal,
  AIFinding,
  Incident,
  SecurityRecommendationData,
  CallRecord,
  TrustedContact,
  VerificationChallenge,
  OverviewMetric,
  ThreatDistributionItem,
} from "@/types/dashboard";

export const MOCK_OVERVIEW_METRICS: OverviewMetric[] = [
  {
    id: "metric-calls",
    label: "Calls Monitored (24h)",
    value: "1,429",
    subtext: "+12.4% vs 7-day average",
    trend: { direction: "up", value: "+12.4%", isPositive: true },
    status: "normal",
  },
  {
    id: "metric-flagged",
    label: "Suspicious Calls Flagged",
    value: "18",
    subtext: "1.25% anomaly screening rate",
    trend: { direction: "down", value: "-4.2%", isPositive: true },
    status: "warning",
  },
  {
    id: "metric-intercepted",
    label: "Impersonations Blocked",
    value: "4",
    subtext: "100% containment rate",
    trend: { direction: "up", value: "+1", isPositive: true },
    status: "critical",
  },
  {
    id: "metric-prevented-loss",
    label: "Protected Capital",
    value: "$620,000",
    subtext: "Thwarted fraudulent wire transfers",
    trend: { direction: "up", value: "+$180k", isPositive: true },
    status: "active",
  },
];

export const MOCK_LIVE_CALL: LiveCall = {
  id: "call-live-8921",
  sessionId: "VS-2026-000241",
  callerName: "Rahul Sharma (Claimed)",
  callerRole: "Chief Financial Officer",
  callerNumber: "+91 98201 44521",
  duration: "03:42",
  status: "LIVE ANALYSIS",
  verificationState: "CHALLENGED",
  overallRiskScore: 88,
  riskLevel: "CRITICAL",
  startTime: "23:24:10 UTC",
  telephonyTrunk: "Trunk SIP-NY-04 (Inbound Direct)",
};

export const MOCK_RISK_SIGNALS: RiskSignal[] = [
  {
    id: "sig-voice-integrity",
    label: "Voice Authenticity",
    score: 84,
    weight: 0.35,
    riskLevel: "CRITICAL",
    confidenceLabel: "96% CONFIDENCE",
    description: "Synthetic Vocoder & Phase Artifact Detection",
    textInterpretation: "Strong synthetic vocoder phase boundaries detected.",
    explanation: "Neural acoustic model identified high-frequency spectral phase discontinuities typical of diffusion-based voice conversion models.",
    technicalDetails: [
      "Acoustic phase coherence: 0.22 (Threshold > 0.70)",
      "High-frequency pitch contour jitter: 4.8 Hz",
      "Vocoder spectral signature: Matched Diffusion-TTS v4",
    ],
  },
  {
    id: "sig-speaker-consistency",
    label: "Speaker Verification",
    score: 91, // represents mismatch risk
    weight: 0.30,
    riskLevel: "CRITICAL",
    confidenceLabel: "92% CONFIDENCE",
    description: "Biometric Voiceprint Reference Match",
    textInterpretation: "Cosine similarity 0.34 against enrolled Rahul Sharma profile.",
    explanation: "SpeechBrain ECAPA-TDNN 192-dim biometric embedding deviates significantly from the enrolled executive baseline.",
    technicalDetails: [
      "Target Profile: Rahul Sharma (Enrolled Aug 14, 2026)",
      "Embedding Cosine Distance: 0.66 (Mismatch threshold > 0.45)",
      "Vocal tract resonance match: 28%",
    ],
  },
  {
    id: "sig-social-engineering",
    label: "Speech & Intent Risk",
    score: 86,
    weight: 0.25,
    riskLevel: "CRITICAL",
    confidenceLabel: "94% CONFIDENCE",
    description: "Urgency, Coercion & Wire Fraud Semantic Screening",
    textInterpretation: "Explicit demand for $45,000 emergency wire transfer with executive override.",
    explanation: "NLP semantic engine detected urgent financial transaction patterns paired with attempts to bypass standard dual-custody verification.",
    technicalDetails: [
      "Identified Intent: Urgent Wire Authorization ($45,000 USD)",
      "Coercive pressure index: 88/100",
      "Verification bypass attempt: 'Skip standard protocol due to board meeting'",
    ],
  },
  {
    id: "sig-context-risk",
    label: "Caller & Context Risk",
    score: 65,
    weight: 0.10,
    riskLevel: "HIGH",
    confidenceLabel: "88% CONFIDENCE",
    description: "Carrier Routing, Telecom Metadata & Origin Analysis",
    textInterpretation: "Caller ID matches enrolled number, but carrier originates from VoIP wholesale trunk.",
    explanation: "Telephony metadata indicates SIP trunk spoofing. Physical tower ping does not correlate with known executive location.",
    technicalDetails: [
      "Caller ID: +91 98201 44521 (Spoofed)",
      "Originating Carrier: Wholesale VoIP Gateway LLC",
      "STIR/SHAKEN Attestation: Level C (Gateway unverified)",
    ],
  },
];

export const MOCK_DETECTION_EVENTS: AIFinding[] = [
  {
    id: "find-1",
    title: "Synthetic vocoder phase discrepancy",
    signalSource: "VOICE INTEGRITY",
    severity: "CRITICAL",
    timestamp: "00:18",
    details: "Abrupt spectral phase discontinuity detected at 4.2 kHz boundary.",
    category: "SYNTHETIC_ARTIFACT",
  },
  {
    id: "find-2",
    title: "Biometric voiceprint mismatch",
    signalSource: "SPEAKER VERIFICATION",
    severity: "CRITICAL",
    timestamp: "00:32",
    details: "Embedding distance (0.66) exceeded security cutoff (0.45) for enrolled profile Rahul Sharma.",
    category: "BIOMETRIC_MISMATCH",
  },
  {
    id: "find-3",
    title: "Urgent $45k financial transfer demanded",
    signalSource: "CONVERSATION ANALYSIS",
    severity: "CRITICAL",
    timestamp: "00:54",
    details: "Caller explicitly requested immediate off-ledger wire transfer to unverified vendor routing number.",
    category: "COERCION_URGENCY",
  },
  {
    id: "find-4",
    title: "Carrier STIR/SHAKEN Attestation Level C",
    signalSource: "CONTEXT ENGINE",
    severity: "HIGH",
    timestamp: "01:05",
    details: "Inbound telephony trunk originates from high-risk virtual VoIP provider without cryptographic certificate.",
    category: "CARRIER_ANOMALY",
  },
  {
    id: "find-5",
    title: "Verification bypass assertion",
    signalSource: "CONVERSATION ANALYSIS",
    severity: "CRITICAL",
    timestamp: "01:22",
    details: "Caller claimed executive emergency exemption to circumvent standard 2-person authorization.",
    category: "POLICY_VIOLATION",
  },
];

export const MOCK_RECOMMENDATION: SecurityRecommendationData = {
  title: "Do not trust the caller's identity",
  description:
    "High-confidence synthetic audio artifacts and severe biometric mismatch detected. The caller is attempting to execute an unauthorized $45,000 wire transfer.",
  triggeringSignals: "Voice Authenticity (84) + Speaker Mismatch (91) + Financial Intent (86)",
  urgency: "CRITICAL",
  primaryAction: {
    id: "action-verify",
    label: "Verify Caller via Out-of-Band Channel",
    actionType: "VERIFY_CALLER",
  },
  secondaryActions: [
    { id: "act-safe-word", label: "Challenge with Pre-Shared Safe Word", actionType: "SAFE_WORD" },
    { id: "act-callback", label: "Dial Verified Emergency Callback Line", actionType: "CALLBACK" },
    { id: "act-freeze", label: "Freeze Sensitive Transaction Queue", actionType: "FREEZE_TX" },
    { id: "act-terminate", label: "Terminate Call & Escalate Incident", actionType: "TERMINATE" },
  ],
};

export const MOCK_RECENT_INCIDENTS: Incident[] = [
  {
    id: "INC-2026-000241",
    timestamp: "5m ago",
    caller: "Rahul Sharma (Claimed)",
    callerNumber: "+91 98201 44521",
    callerRole: "Chief Financial Officer",
    riskLevel: "CRITICAL",
    riskScore: 88,
    primaryFinding: "AI Voice Clone + Urgent $45,000 Wire Request",
    status: "INVESTIGATING",
    assignedAnalyst: "David Zhao (SOC Lead)",
    containmentAction: "Wire Queue Locked; Safe Word Challenge Failed",
    summary: "Targeted deepfake impersonation of Chief Financial Officer attempting to authorize fraudulent international wire transfer.",
    timeline: [
      { id: "t-1", timestamp: "18:24:10", title: "Inbound Call Established", description: "Call routed through SIP-NY-04 trunk.", severity: "LOW", source: "PBX" },
      { id: "t-2", timestamp: "18:24:28", title: "Acoustic Anomaly Flagged", description: "Vocoder phase discontinuity detected.", severity: "HIGH", source: "Voice Engine" },
      { id: "t-3", timestamp: "18:24:42", title: "Biometric Mismatch Confirmed", description: "Cosine similarity 0.34 against baseline.", severity: "CRITICAL", source: "Biometrics" },
      { id: "t-4", timestamp: "18:25:04", title: "Safe Word Challenge Issued", description: "Operator prompted for safe word; caller disconnected.", severity: "CRITICAL", source: "Analyst" },
    ],
    notes: [
      { id: "n-1", author: "David Zhao", role: "SOC Lead", timestamp: "18:28", content: "Confirmed synthetic speech pattern matching recent ElevenLabs v2 voice clone signatures. Notified treasury team to blacklist recipient account." },
    ],
    evidence: {
      vocoderDiscrepancies: "Phase discontinuities at 4.2 kHz and unnatural pitch contour jitter.",
      biometricScore: 0.34,
      flaggedPhrases: ["wire immediately", "skip compliance", "board emergency", "vendor escrow"],
      callerIpLocation: "Frankfurt, Germany (Wholesale VoIP)",
      carrierName: "VoIP Gateway LLC (STIR/SHAKEN Level C)",
    },
  },
  {
    id: "INC-2026-000239",
    timestamp: "1h ago",
    caller: "Finance Dept Lead (Claimed)",
    callerNumber: "+1 (555) 908-1122",
    callerRole: "VP Treasury",
    riskLevel: "CRITICAL",
    riskScore: 92,
    primaryFinding: "Voice Clone & Admin Credential Harvesting",
    status: "CONTAINED",
    assignedAnalyst: "Sarah Jenkins (Fraud Analyst)",
    containmentAction: "Okta Admin Sessions Revoked",
    summary: "Impersonator called corporate IT helpdesk requesting temporary MFA bypass for administrative portal access.",
    evidence: {
      vocoderDiscrepancies: "Neural pitch artifacts detected at 2.8 kHz.",
      biometricScore: 0.28,
      flaggedPhrases: ["lost my phone", "bypass Okta push", "urgent payroll deadline"],
      callerIpLocation: "Toronto, Canada",
      carrierName: "Bandwidth.com (Spoofed)",
    },
  },
  {
    id: "INC-2026-000224",
    timestamp: "4h ago",
    caller: "IT Helpdesk Spoof",
    callerNumber: "+1 (555) 334-0099",
    callerRole: "External Inbound",
    riskLevel: "HIGH",
    riskScore: 68,
    primaryFinding: "Unregistered Line & Social Engineering Pressure",
    status: "RESOLVED",
    assignedAnalyst: "Marcus Chen",
    containmentAction: "Employee Advised; Attestation Logged",
    summary: "Social engineering vishing campaign targeting junior accounting staff.",
  },
  {
    id: "INC-2026-000215",
    timestamp: "Yesterday",
    caller: "Elena Rostova (Operations)",
    callerNumber: "+1 (555) 678-1234",
    callerRole: "VP Global Operations",
    riskLevel: "MEDIUM",
    riskScore: 42,
    primaryFinding: "Poor Signal-to-Noise Ratio & Audio Distortions",
    status: "FALSE_POSITIVE",
    assignedAnalyst: "David Zhao",
    containmentAction: "Voiceprint Enrolled; Profile Calibrated",
    summary: "Executive was calling from airport terminal with severe background reverberation.",
  },
  {
    id: "INC-2026-000201",
    timestamp: "2 days ago",
    caller: "Vendor Wire Representative",
    callerNumber: "+1 (555) 776-4433",
    callerRole: "External Supplier",
    riskLevel: "LOW",
    riskScore: 14,
    primaryFinding: "Routine Account Confirmation - Verified",
    status: "RESOLVED",
    assignedAnalyst: "Automated Rule",
    containmentAction: "Cleared without Escalation",
    summary: "Scheduled vendor invoice verification call adhering to pre-cleared standard protocols.",
  },
];

export const MOCK_CALL_HISTORY: CallRecord[] = [
  {
    id: "CALL-2026-8921",
    sessionId: "VS-2026-000241",
    callerName: "Rahul Sharma (Claimed)",
    callerNumber: "+91 98201 44521",
    callerRole: "Chief Financial Officer",
    timestamp: "Today, 18:24 UTC",
    duration: "03:42",
    riskScore: 88,
    riskLevel: "CRITICAL",
    primaryTrigger: "Voice Clone Impersonation & Wire Request",
    disposition: "INTERCEPTED",
    transcriptHighlights: [
      { time: "00:12", speaker: "AGENT", text: "Executive Treasury Desk, this is Rachel. How can I help?", risk: "LOW" },
      { time: "00:18", speaker: "CALLER", text: "Rachel, it's Rahul Sharma. I'm in closed-door sessions with our European partners.", category: "IDENTITY_CLAIM", risk: "MEDIUM" },
      { time: "00:34", speaker: "CALLER", text: "We need an emergency $45,000 wire released to our Zurich escrow account immediately.", category: "FINANCIAL_REQUEST", risk: "CRITICAL" },
      { time: "00:52", speaker: "AGENT", text: "Mr. Sharma, standard protocol requires a verbal safe word for off-ledger wires.", risk: "LOW" },
      { time: "01:05", speaker: "CALLER", text: "I don't have time for safe words! The deal collapses if the funds aren't cleared by 5 PM.", category: "URGENCY", risk: "CRITICAL" },
      { time: "01:24", speaker: "CALLER", text: "Bypass the dual authorization and mark it as my personal executive override.", category: "AUTH_BYPASS", risk: "CRITICAL" },
    ],
    signalsSummary: {
      voiceIntegrityScore: 84,
      speakerMatchScore: 91,
      socialEngineeringScore: 86,
      contextRiskScore: 65,
    },
  },
  {
    id: "CALL-2026-8919",
    sessionId: "VS-2026-000239",
    callerName: "Sarah Lin",
    callerNumber: "+1 (555) 902-8811",
    callerRole: "Chief Financial Officer",
    timestamp: "Today, 16:15 UTC",
    duration: "06:12",
    riskScore: 12,
    riskLevel: "LOW",
    primaryTrigger: "Normal Parameters - Biometric Verified",
    disposition: "CLEARED",
    signalsSummary: {
      voiceIntegrityScore: 8,
      speakerMatchScore: 12,
      socialEngineeringScore: 5,
      contextRiskScore: 14,
    },
  },
  {
    id: "CALL-2026-8910",
    sessionId: "VS-2026-000230",
    callerName: "Marcus Wright",
    callerNumber: "+1 (555) 334-0099",
    callerRole: "Lead Legal Counsel",
    timestamp: "Today, 14:02 UTC",
    duration: "02:18",
    riskScore: 18,
    riskLevel: "LOW",
    primaryTrigger: "Verified Legal Trunk",
    disposition: "CLEARED",
  },
  {
    id: "CALL-2026-8898",
    sessionId: "VS-2026-000224",
    callerName: "IT Support Desk",
    callerNumber: "+1 (555) 880-9911",
    callerRole: "Internal Contractor",
    timestamp: "Yesterday, 21:40 UTC",
    duration: "04:05",
    riskScore: 68,
    riskLevel: "HIGH",
    primaryTrigger: "Unrecognized Carrier + Password Reset Intent",
    disposition: "CHALLENGED_VERIFIED",
  },
  {
    id: "CALL-2026-8876",
    sessionId: "VS-2026-000210",
    callerName: "Elena Rostova",
    callerNumber: "+1 (555) 678-1234",
    callerRole: "VP Global Operations",
    timestamp: "Yesterday, 17:30 UTC",
    duration: "01:45",
    riskScore: 42,
    riskLevel: "MEDIUM",
    primaryTrigger: "Acoustic Noise - Airport Reverberation",
    disposition: "CLEARED",
  },
];

export const MOCK_TRUSTED_CONTACTS: TrustedContact[] = [
  {
    id: "cnt-1",
    name: "Rahul Sharma",
    role: "Chief Financial Officer",
    phone: "+91 98201 44521",
    enrolledDate: "Aug 14, 2026",
    sampleDuration: "32.4s (High Quality)",
    voiceprintStatus: "VERIFIED",
    embeddingHash: "ecapa_tdnn_9f82ab11c389",
    safeWordMasked: "••••••••••••",
    safeWordPlain: "COBALT-ORION-77",
    emergencyCallback: "+91 98201 99999",
    verificationPolicy: "Strict Out-of-Band Callback for transactions > $10,000",
  },
  {
    id: "cnt-2",
    name: "Sarah Lin",
    role: "VP Treasury & Operations",
    phone: "+1 (555) 902-8811",
    enrolledDate: "Jul 28, 2026",
    sampleDuration: "45.0s (Studio Grade)",
    voiceprintStatus: "VERIFIED",
    embeddingHash: "ecapa_tdnn_33cc092b7712",
    safeWordMasked: "••••••••••••",
    safeWordPlain: "AEGIS-SUMMIT-42",
    emergencyCallback: "+1 (555) 902-0001",
    verificationPolicy: "Dual-Auth Verification on all wire desk requests",
  },
  {
    id: "cnt-3",
    name: "Marcus Wright",
    role: "Lead Legal Counsel",
    phone: "+1 (555) 334-0099",
    enrolledDate: "Sep 01, 2026",
    sampleDuration: "24.2s (Standard)",
    voiceprintStatus: "VERIFIED",
    embeddingHash: "ecapa_tdnn_7811ef445582",
    safeWordMasked: "••••••••••••",
    safeWordPlain: "LEX-VERITAS-19",
    emergencyCallback: "+1 (555) 334-7700",
    verificationPolicy: "Step-Up Push MFA required for contract approvals",
  },
  {
    id: "cnt-4",
    name: "Elena Rostova",
    role: "VP Global Operations",
    phone: "+1 (555) 678-1234",
    enrolledDate: "Pending Enrollment",
    sampleDuration: "0.0s (Unenrolled)",
    voiceprintStatus: "PENDING_ENROLLMENT",
    embeddingHash: "unregistered_pending_sample",
    safeWordMasked: "••••••••••••",
    safeWordPlain: "PHOENIX-DELTA-88",
    emergencyCallback: "+1 (555) 678-9900",
    verificationPolicy: "Default High-Risk Screening Protocol",
  },
];

export const MOCK_VERIFICATION_CHALLENGES: VerificationChallenge[] = [
  {
    id: "CHL-2026-091",
    timestamp: "18:25:04 UTC",
    callerName: "Rahul Sharma (Claimed)",
    callerPhone: "+91 98201 44521",
    challengeType: "SAFE_WORD",
    status: "FAILED",
    respondedAt: "18:25:20 UTC",
    riskLevel: "CRITICAL",
    operatorNotes: "Caller became agitated and hung up when asked for pre-shared safe word.",
  },
  {
    id: "CHL-2026-089",
    timestamp: "16:16:10 UTC",
    callerName: "Sarah Lin",
    callerPhone: "+1 (555) 902-8811",
    challengeType: "OUT_OF_BAND_CALLBACK",
    status: "PASSED",
    respondedAt: "16:16:45 UTC",
    riskLevel: "LOW",
    operatorNotes: "Callback completed to secure corporate desk line; biometric identity verified.",
  },
  {
    id: "CHL-2026-084",
    timestamp: "14:10:00 UTC",
    callerName: "Marcus Wright",
    callerPhone: "+1 (555) 334-0099",
    challengeType: "STEP_UP_MFA",
    status: "PASSED",
    respondedAt: "14:10:18 UTC",
    riskLevel: "LOW",
    operatorNotes: "FIDO2 hardware key challenge approved via mobile authenticator.",
  },
];

export const MOCK_THREAT_DISTRIBUTION: ThreatDistributionItem[] = [
  { category: "Generative AI Voice Clones", percentage: 52, count: 28, trend: "+18% this month", color: "#EF4444" },
  { category: "Caller-ID & SIP Trunk Spoofing", percentage: 26, count: 14, trend: "+4% this month", color: "#F97316" },
  { category: "Social Engineering & Coercion", percentage: 14, count: 8, trend: "-2% this month", color: "#F59E0B" },
  { category: "Acoustic Replay / Pre-recorded", percentage: 8, count: 4, trend: "Stable", color: "#38BDF8" },
];
